Remove default value for sku_name variable.
hmcts/cnp-module-redis pull request #43
Opened 2023-10-05 11:53 UTC by mokainos

Resolves # . (This is applicable only if this pull request relates to a GitHub issue, delete the line otherwise)

Notes:
*
*
*

2023-10-05 11:54 UTC, timja commented on README.md
> +Premium redis PaaS instance are very expensive, care **must** be taken when using them and only used in required environments.
is there a nagger in place?

2023-10-05 14:41 UTC, timja commented on README.md
> +}
these should all have defaults set for non production

2023-10-05 14:41 UTC, timja commented on README.md
> +aat.tfvars
probably not needed I would just add prod

2023-10-05 14:44 UTC, timja requested changes

2023-10-05 14:44 UTC, timja commented on variables.tf
> +  default     = "C"
🚫 This is a breaking change and can't be done without a nagger in place first and even then I think you would just want to remove the default

2023-10-05 14:44 UTC, timja commented on variables.tf
> +  default     = "Basic"
🚫 This is a breaking change and can't be done without a nagger in place first and even then I think you would just want to remove the default

2023-10-05 14:44 UTC, timja commented on variables.tf
> +  default     = "3"
Why change this to 3?

2024-06-24 08:37 UTC, madjava commented
Closing PR for now

2024-06-24 08:37 UTC, closed without merging